### ISSUE TITLE
Incorrect MIME-type for TSV-file inputs

### ISSUE THREAD

**Issue by ebete** [nf-core/ampliseq#831]
### Description of the bug

The MIME-types for TSV files in [nextflow_schema.json](https://github.com/nf-core/ampliseq/blob/2.12.0/nextflow_schema.json) are set to `text/tsv` instead of `text/tab-separated-values` (see: [IANA tsv](https://www.iana.org/assignments/media-types/text/tab-separated-values)).

- https://github.com/nf-core/ampliseq/blob/2.12.0/nextflow_schema.json#L17
- https://github.com/nf-core/ampliseq/blob/2.12.0/nextflow_schema.json#L26
- https://github.com/nf-core/ampliseq/blob/2.12.0/nextflow_schema.json#L60

This causes issues within Seqera cloud, as TSV-files uploaded using the Datasets tab will have the `text/tab-separated-values` MIME-type, and will thus not be selectable as an input for the pipeline as it doesn't match `text/tsv`.

See Seqera platform docs regarding this feature:
https://docs.seqera.io/platform/24.3/data/datasets#use-a-dataset

### Command used and terminal output

```console

```

### System information

- Seqera cloud: `24.2.3_5387adb`
- nf-core/ampliseq: `2.12.0`

**Comment by pinin4fjords** [comment]
Actually the Platform incompatibility is more to do with the lack of pattern specification in the schema- could be fixed like https://github.com/nf-core/ampliseq/pull/832.

**Comment by d4straub** [comment]
The problem is solved for --input in the dev branch. However, all params that point to files should have patterns to make them work, so I keep the issue open as reminder.

**Comment by ebete** [comment]
It looks like TSV datasets are still not selectable from the dropdown within Seqera Platform when using the `dev` branch. But I'm also not sure if the platform uses extensions for matching datasets, and instead opts for MIME-types. At least in the front-end, the extension is stripped from dataset names.

**Comment by pinin4fjords** [comment]
> It looks like TSV datasets are still not selectable from the dropdown within Seqera Platform when using the `dev` branch. But I'm also not sure if the platform uses extensions for matching datasets, and instead opts for MIME-types. At least in the front-end, the extension is stripped from dataset names.

Yes, there are two issues here. 

1. Lack of a pattern means Platform doesn't respond correctly (fixed in the linked issue)
2. Platform doesn't respond correctly to patterns with the multiple extensions required here. This is a bug in Platform itself and will need to be resolved there. 

The only viable workaround right now is to reset the schema to use a single file extension in the pattern. You could override the schema yourself pending the fix to the above.

**Comment by d4straub** [comment]
Ok I added the pattern to the other input files. Now just the Platform needs to be fixed :)
